# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-21 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kunsido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.IntegerField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('rsvp_cutoff', models.IntegerField()),
                ('new_players', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'kunsidoj',
            },
        ),
        migrations.CreateModel(
            name='Ludanto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(max_length=200)),
                ('when', models.CharField(choices=[('Sunday', 'Morning'), ('Sunday', 'Afternoon'), ('Sunday', 'Evening'), ('Sunday', 'Night'), ('Monday', 'Morning'), ('Monday', 'Afternoon'), ('Monday', 'Evening'), ('Monday', 'Night'), ('Tuesday', 'Morning'), ('Tuesday', 'Afternoon'), ('Tuesday', 'Evening'), ('Tuesday', 'Night'), ('Wednesday', 'Morning'), ('Wednesday', 'Afternoon'), ('Wednesday', 'Evening'), ('Wednesday', 'Night'), ('Thursday', 'Morning'), ('Thursday', 'Afternoon'), ('Thursday', 'Evening'), ('Thursday', 'Night'), ('Friday', 'Morning'), ('Friday', 'Afternoon'), ('Friday', 'Evening'), ('Friday', 'Night'), ('Saturday', 'Morning'), ('Saturday', 'Afternoon'), ('Saturday', 'Evening'), ('Saturday', 'Night')], max_length=200)),
            ],
            options={
                'verbose_name_plural': 'ludantoj',
            },
        ),
        migrations.CreateModel(
            name='Ludo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'ludoj',
            },
        ),
        migrations.CreateModel(
            name='Mastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(max_length=200)),
                ('when', models.CharField(max_length=200)),
                ('games', models.ManyToManyField(to='tablo.Ludo')),
            ],
            options={
                'verbose_name_plural': 'mastroj',
            },
        ),
        migrations.AddField(
            model_name='ludanto',
            name='games',
            field=models.ManyToManyField(to='tablo.Ludo'),
        ),
        migrations.AddField(
            model_name='kunsido',
            name='game',
            field=models.ManyToManyField(to='tablo.Ludo'),
        ),
        migrations.AddField(
            model_name='kunsido',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablo.Mastro'),
        ),
        migrations.AddField(
            model_name='kunsido',
            name='players',
            field=models.ManyToManyField(to='tablo.Ludanto'),
        ),
    ]
